package com.bank.islamic.sukukportfoliomanagement;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Sukuk Portfolio Management
 *
 * Business Area:      Treasury Markets and Sukuk
 * Business Domain:    Sukuk
 * Functional Pattern: Manage
 * Asset Type:         Sukuk Portfolio
 * Control Record:     Sukuk Portfolio Management Plan
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Sukuk Portfolio Management — BIAN Semantic API")
                .description("Service Domain 'Sukuk Portfolio Management' (Manage pattern) "
                        + "operating on the 'Sukuk Portfolio Management Plan' control record.")
                .version("0.1.0"));
    }
}
